version: 1
applications:
  - appRoot: apps/public-site
    frontend:
      buildPath: /
      phases:
        preBuild:
          commands:
            - nvm install 24
            - nvm use 24
            - npm ci
        build:
          commands:
            - npm run build:public
      artifacts:
        baseDirectory: apps/public-site/.next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          - apps/public-site/.next/cache/**/*
