import { LegalPage } from "../components/LegalPage";
import { createLegalMetadata } from "../lib/legal-metadata";

export const metadata = createLegalMetadata({
  title: "Privacy notice",
  description:
    "How SozoRock Health handles information across its public website and non-clinical readiness experiences.",
  path: "/privacy",
});

export default function PrivacyPage() {
  return (
    <LegalPage eyebrow="Public policy" title="Privacy notice" updated="August 24, 2026">
      <h2>Our approach</h2>
      <p>SozoRock Health is an initiative of The SozoRock Foundation, Inc. We collect only the information reasonably needed to respond to a request, provide a feature a person chooses, protect our services, or understand whether public information is useful. This website is not a place to submit medical records, diagnoses, insurance identifiers, or urgent health information.</p>
      <h2>Information you choose to provide</h2>
      <p>A contact, partnership, volunteer, or publication-access request may include your name, email address, organization, role or sector, location, reason for interest, message, and the consent choices shown on the form. We use this information to fulfill the request, communicate with you, prevent misuse, evaluate the quality and reach of publication access, and maintain an appropriate record of the interaction. Publication access requires confirmation of the email address used for the request before a secure download session is created. Receiving future publication updates is optional and is not a condition of accessing a requested publication.</p>
      <h2>Publication access and attribution</h2>
      <p>For publication access, we may also record limited first-party attribution and technical context such as the page where a visit began, referring website, campaign parameters included in a SozoRock link, browser and operating-system family, device class, interface language, time zone, and coarse country or region information supplied by our hosting network. A random first-party visitor identifier may be stored in your browser so repeat access attempts can be measured and abuse controls applied without storing a raw network address with the request. We may assign internal quality indicators to publication-access records based on signals such as whether an email was verified, whether submitted text appears to be placeholder or automated input, whether location fields are internally consistent, and whether requests occur unusually quickly or repeatedly. These indicators support data-quality review and service protection; they are not identity proof and are not used for clinical, insurance, employment, credit, or eligibility decisions.</p>
      <h2>Resident Access Layer and mobile app</h2>
      <p>When you choose to send a non-clinical readiness request from the mobile app or a shared tablet, we receive only the journey you selected, a ZIP code or Health Equity Hub reference, the non-clinical support option you selected, the interface language, whether the request came from the mobile or kiosk experience, and the consent record shown before submission. We do not ask for your name, email address, medical history, symptoms, diagnosis, treatment information, insurance details, or other protected health information in this flow. Sending a request does not create a provider relationship, confirm eligibility, or connect you to a licensed provider.</p>
      <h2>Website and security information</h2>
      <p>Our hosting and security services may process limited technical information such as the date and time of a request, browser or device type, requested page, referring page, campaign source, and network address. We use this information to operate the website, diagnose errors, measure general use, and protect against automated abuse. Rate-limiting and publication-access records use a salted, one-way representation of a network address where a durable abuse identifier is needed; the raw network address is not stored with the publication request by the application.</p>
      <h2>Voice Access</h2>
      <p>Microphone access begins only after you review the voice notice and agree. On the website, OpenAI processes microphone audio during the live, non-clinical Voice Access session. OpenAI states that API data is not used to train its models by default. Unless different data controls are approved for the project, content may be retained in abuse-monitoring logs for up to 30 days under <a href="https://platform.openai.com/docs/guides/your-data" rel="noreferrer">OpenAI&apos;s API data-controls policy</a>. In the mobile app, speech recognition may use the speech service available on the Apple or Android device and may be processed under Apple&apos;s, Google&apos;s, or the device provider&apos;s terms. SozoRock Health does not send a device-speech transcript to its access-request API or store it with a request. Do not share medical records or protected health information. You can stop a session at any time, and text or tap options remain available. SozoRock Health does not intentionally record or retain raw microphone audio.</p>
      <h2>How information is shared</h2>
      <p>We may share information with service providers that operate the website, protect it, deliver requested email, or support an approved feature. They may use the information only to provide those services under appropriate safeguards. We may also disclose information when required by law, to protect people or our services, or as part of an organizational transaction permitted by law. We do not sell personal information or use it for behavioral advertising.</p>
      <h2>Retention and security</h2>
      <p>Contact inquiries are scheduled for deletion after one year unless they become part of an active relationship or a longer period is required by law. Resident Access Layer requests and their consent records are scheduled for deletion after 30 days. Their short-lived abuse-prevention records use a salted, one-way representation of a network address and expire separately; the network address is not stored with the request. Publication-access requests, consent records, attribution context, quality indicators, and related activity records are scheduled for deletion after 180 days. Verification links expire after 30 minutes and verified secure-access sessions after 12 hours. We use administrative, technical, and organizational safeguards appropriate to the information, but no internet service can guarantee absolute security.</p>
      <h2>County-Based Community Access Platform</h2>
      <p>The County-Based Community Access Platform (CB-CAP) is designed to keep individual-facing support separate from county-level systems intelligence. Dashboard views and reports use aggregated, de-identified pathway information. Small groups are withheld when the approved privacy threshold is not met. CB-CAP is not intended to expose individual-level protected health information.</p>
      <h2>Children and external services</h2>
      <p>This public website is intended for a general audience and is not designed to collect personal information directly from children under 13. Links to provider, public-agency, social-media, and other external services lead to sites with their own privacy practices.</p>
      <h2>Your choices</h2>
      <p>You may ask to access, correct, or delete information you submitted, or withdraw an optional communications choice, subject to identity verification and legal, security, and operational obligations. Email <a href="mailto:contact@sozorockfoundation.org">contact@sozorockfoundation.org</a> and describe your request. We may update this notice as the service changes and will post the revision date on this page.</p>
    </LegalPage>
  );
}
