"use client";

import {useMemo, useState} from "react";
import {
  aggregateCountyRecords, cbcapSeedMetadata, countyAccessSeed, countyRecordsToCsv,
  disclosureControl, filterCountyRecords, type CountyFilters,
} from "@sozorock/domain";

const initialFilters: CountyFilters = {state:"All states",county:"All counties",zip:"All ZIP codes",period:"All periods",hubType:"All hub types",language:"All languages"};
const unique = (items: string[]) => [...new Set(items)].sort();

function downloadFile(contents:string, filename:string, type:string) {
  const url=URL.createObjectURL(new Blob([contents],{type}));
  const anchor=document.createElement("a"); anchor.href=url; anchor.download=filename; anchor.click(); URL.revokeObjectURL(url);
}

function SelectFilter({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}) {
  return <label className="filter"><span>{label}</span><select value={value} onChange={(event)=>onChange(event.target.value)}>{options.map((option)=><option key={option}>{option}</option>)}</select></label>;
}

function TrendChart({values}:{values:number[]}) {
  const data=values.length?values:[0], width=640, height=220, max=Math.max(...data,1);
  const coords=data.map((value,index)=>({value,x:28+index*((width-56)/Math.max(data.length-1,1)),y:height-34-(value/max)*(height-72)}));
  const points=coords.map(({x,y})=>`${x},${y}`).join(" ");
  return <svg className="trend-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Connection requests by visible record: ${data.join(", ")}`}>
    {[0,1,2,3].map((line)=><line key={line} x1="28" x2={width-28} y1={30+line*45} y2={30+line*45} className="gridline"/>)}
    <polyline points={points} className="trend-line-shadow"/><polyline points={points} className="trend-line"/>
    {coords.map(({value,x,y},index)=><g key={`${value}-${index}`}><circle cx={x} cy={y} r="5"/><text x={x} y={y-12} textAnchor="middle">{value}</text></g>)}
  </svg>;
}

function AccessMap({records}:{records:typeof countyAccessSeed}) {
  const scores=unique(records.map((record)=>record.stateCode)).map((stateCode)=>{const matching=records.filter((record)=>record.stateCode===stateCode);return {stateCode,score:Math.round(matching.reduce((sum,item)=>sum+item.accessIndex,0)/matching.length)};});
  const positions:Record<string,[number,number]>={CA:[70,112],TX:[245,180],NM:[183,153],KY:[356,119],NY:[455,58]};
  return <div className="map-frame" role="img" aria-label="Schematic United States view of access index for filtered seed-data states"><svg viewBox="0 0 520 250" aria-hidden="true"><path className="country" d="M32 73L82 52l63 11 36-24 71 13 33-17 45 19 70-1 55 30 32 34-28 20-19 44-51 10-38 24-73-5-52 24-52-15-61 3-19-40-39-22z"/>{scores.map(({stateCode,score})=>{const [x,y]=positions[stateCode]??[260,125];return <g key={stateCode}><circle cx={x} cy={y} r={10+score/9} style={{opacity:.25+score/140}}/><text x={x} y={y+4} textAnchor="middle">{stateCode}</text></g>;})}</svg>{!records.length&&<p>No visible geography matches these filters.</p>}</div>;
}

export default function Platform() {
  const [filters,setFilters]=useState(initialFilters), [activeView,setActiveView]=useState("Overview"), [toast,setToast]=useState("");
  const stateRecords=useMemo(()=>countyAccessSeed.filter((record)=>filters.state==="All states"||record.state===filters.state),[filters.state]);
  const countyRecords=useMemo(()=>stateRecords.filter((record)=>filters.county==="All counties"||record.county===filters.county),[stateRecords,filters.county]);
  const filtered=useMemo(()=>filterCountyRecords(countyAccessSeed,filters),[filters]);
  const summary=useMemo(()=>aggregateCountyRecords(filtered),[filtered]);
  const topBarriers=useMemo(()=>{const labels={transportation:"Transportation",cost:"Cost",information:"Information gap",digital:"Digital access",language:"Language"};return Object.entries(labels).map(([key,label])=>({label,value:summary.visible.length?Math.round(summary.visible.reduce((sum,record)=>sum+record.barriers[key as keyof typeof record.barriers],0)/summary.visible.length):0})).sort((a,b)=>b.value-a.value);},[summary.visible]);
  const updateFilter=(key:keyof CountyFilters,value:string)=>{setToast("");setFilters((current)=>({...current,[key]:value,...(key==="state"?{county:"All counties",zip:"All ZIP codes"}:{}),...(key==="county"?{zip:"All ZIP codes"}:{})}));};
  const exportCsv=()=>{if(!summary.visible.length)return setToast("No disclosure-safe rows are available to export.");downloadFile(`# ${cbcapSeedMetadata.source}\n# ${cbcapSeedMetadata.note}\n${countyRecordsToCsv(filtered)}`,"cbcap-illustrative-export.csv","text/csv;charset=utf-8");setToast(`CSV downloaded with ${summary.visible.length} disclosure-safe row${summary.visible.length===1?"":"s"}.`);};
  const downloadBrief=()=>{const filterText=Object.entries(filters).map(([key,value])=>`${key}: ${value}`).join("\n");const brief=`CB-CAP ACCESS BRIEF — ILLUSTRATIVE DATA\nGenerated: ${new Date().toLocaleDateString()}\n\n${cbcapSeedMetadata.note}\nSuppression threshold: fewer than ${disclosureControl.minimumCellSize} observations\n\nFILTERS\n${filterText}\n\nVISIBLE SUMMARY\nSample represented: ${summary.sampleSize}\nConnection requests: ${summary.totalRequests}\nCompleted pathways: ${summary.completedPathways}\nCompletion rate: ${summary.completionRate}%\nMedian connection time: ${summary.medianMinutes} minutes\nAccess index: ${summary.accessIndex}/100\nHubs represented: ${summary.hubs}\nSuppressed cells: ${summary.suppressedCount}\n`;downloadFile(brief,"cbcap-illustrative-brief.txt","text/plain;charset=utf-8");setToast("Accessible summary brief downloaded.");};

  return <main className="shell"><aside className="rail"><div className="brand"><span>SozoRock</span><small>HEALTH</small></div><div className="product"><strong>CB-CAP</strong><span>County-Based Community<br/>Access Platform</span></div><nav aria-label="CB-CAP sections">{["Overview","Map","Timeline","Access points","Providers","Reports","Data notes"].map((item)=><button key={item} className={activeView===item?"active":""} onClick={()=>{setActiveView(item);setToast(`${item} selected. Detailed modules connect here as production data services come online.`);}}><span aria-hidden="true">{item==="Overview"?"◫":item==="Map"?"⌖":item==="Timeline"?"⌁":"○"}</span>{item}</button>)}</nav><div className="rail-foot"><span className="status-dot"/> Demonstration workspace<small>Illustrative, non-clinical data</small></div></aside>
  <section className="workspace"><header className="topbar"><div><p className="eyebrow">National access intelligence</p><h1>{filters.county!=="All counties"?filters.county:filters.state!=="All states"?filters.state:"Nationwide overview"}</h1><p className="lede">See where access pathways are forming, where barriers persist, and where communities may need partnership.</p></div><div className="actions"><button className="secondary" onClick={exportCsv}>Export CSV</button><button className="primary" onClick={downloadBrief}>Download brief <span>↓</span></button></div></header>
  <div className="data-banner"><div><strong>Illustrative data</strong><span>Safe seed data demonstrates the product experience; it is not a statement of real county performance.</span></div><small>Refreshed {cbcapSeedMetadata.refreshedAt}</small></div>
  <section className="filter-panel" aria-label="Dashboard filters"><SelectFilter label="State" value={filters.state} options={["All states",...unique(countyAccessSeed.map((record)=>record.state))]} onChange={(value)=>updateFilter("state",value)}/><SelectFilter label="County" value={filters.county} options={["All counties",...unique(stateRecords.map((record)=>record.county))]} onChange={(value)=>updateFilter("county",value)}/><SelectFilter label="ZIP code" value={filters.zip} options={["All ZIP codes",...unique(countyRecords.map((record)=>record.zip))]} onChange={(value)=>updateFilter("zip",value)}/><SelectFilter label="Period" value={filters.period} options={["All periods",...unique(countyAccessSeed.map((record)=>record.period))]} onChange={(value)=>updateFilter("period",value)}/><SelectFilter label="Hub type" value={filters.hubType} options={["All hub types",...unique(countyAccessSeed.map((record)=>record.hubType))]} onChange={(value)=>updateFilter("hubType",value)}/><SelectFilter label="Language" value={filters.language} options={["All languages",...unique(countyAccessSeed.map((record)=>record.language))]} onChange={(value)=>updateFilter("language",value)}/><button className="clear" onClick={()=>{setFilters(initialFilters);setToast("Filters cleared.");}}>Clear all</button></section>
  {toast&&<div className="toast" role="status">{toast}<button aria-label="Dismiss message" onClick={()=>setToast("")}>×</button></div>}
  <section className="metric-grid" aria-label="Filtered access summary"><article><small>People represented</small><strong>{summary.sampleSize.toLocaleString()}</strong><span>Across disclosure-safe cells</span></article><article><small>Connection requests</small><strong>{summary.totalRequests.toLocaleString()}</strong><span>Selected period and geography</span></article><article><small>Completed pathways</small><strong>{summary.completionRate}%</strong><span>{summary.completedPathways.toLocaleString()} completed</span></article><article><small>Median connection time</small><strong>{summary.medianMinutes||"—"}<sup>{summary.medianMinutes?" min":""}</sup></strong><span>Weighted across visible records</span></article><article><small>Access index</small><strong>{summary.accessIndex||"—"}<sup>{summary.accessIndex?"/100":""}</sup></strong><span>Illustrative composite measure</span></article></section>
  <section className="visual-grid"><article className="panel map-panel"><div className="panel-head"><div><p>Geographic pattern</p><h2>Access index by represented state</h2></div><span className="legend"><i/> Higher index</span></div><AccessMap records={summary.visible}/></article><article className="panel trend-panel"><div className="panel-head"><div><p>Movement</p><h2>Connection requests</h2></div><span>Visible record sequence</span></div><TrendChart values={summary.visible.map((record)=>record.connectionRequests)}/></article><article className="panel barriers-panel"><div className="panel-head"><div><p>Barrier profile</p><h2>Top reported barriers</h2></div><span>Average index</span></div>{topBarriers.map((barrier)=><div className="bar-row" key={barrier.label}><span>{barrier.label}</span><div><i style={{width:`${barrier.value}%`}}/></div><b>{barrier.value}</b></div>)}</article><article className="panel table-panel"><div className="panel-head"><div><p>County detail</p><h2>Disclosure-safe records</h2></div><span>{summary.visible.length} visible · {summary.suppressedCount} suppressed</span></div><div className="table-scroll"><table><thead><tr><th>County</th><th>State</th><th>ZIP</th><th>Hub</th><th>Language</th><th>Requests</th><th>Completed</th><th>Index</th></tr></thead><tbody>{summary.visible.map((record)=><tr key={record.id}><td>{record.county}</td><td>{record.stateCode}</td><td>{record.zip}</td><td>{record.hubType}</td><td>{record.language}</td><td>{record.connectionRequests}</td><td>{record.completedPathways}</td><td><b>{record.accessIndex}</b></td></tr>)}{!summary.visible.length&&<tr><td colSpan={8} className="empty">No disclosure-safe records match this view. Try broadening the filters.</td></tr>}</tbody></table></div></article></section>
  <footer className="privacy"><div className="privacy-icon">i</div><div><strong>Privacy threshold applied</strong><p>Cells with fewer than {disclosureControl.minimumCellSize} represented observations are withheld from metrics, charts, tables, and downloads. This demonstration contains no personal or clinical information.</p></div><a href="#data-methodology" onClick={(event)=>{event.preventDefault();setToast("Methodology: synthetic county-level records, minimum-cell suppression, weighted summary measures, and no individual-level data.");}}>View methodology</a></footer></section></main>;
}
