"use client";

import {useEffect, useMemo, useState} from "react";
import dynamic from "next/dynamic";
import {
  aggregateCountyRecords, cbcapSeedMetadata, countyAccessSeed, countyRecordsToCsv,
  disclosureControl, filterCountyRecords, type CountyFilters,
} from "@sozorock/domain";

const initialFilters: CountyFilters = {state:"All states",county:"All counties",zip:"All ZIP codes",period:"All periods",hubType:"All hub types",language:"All languages",barrier:"All barriers",accessRange:"All access levels"};
const unique = (items: string[]) => [...new Set(items)].sort();
const AccessMap=dynamic(()=>import("./AccessMap"),{ssr:false,loading:()=><div className="map-frame map-loading" role="status">Loading county map…</div>});

function downloadFile(contents:string, filename:string, type:string) {
  const url=URL.createObjectURL(new Blob([contents],{type}));
  const anchor=document.createElement("a"); anchor.href=url; anchor.download=filename; anchor.click(); URL.revokeObjectURL(url);
}

function SelectFilter({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}) {
  return <label className="filter"><span>{label}</span><select value={value} onChange={(event)=>onChange(event.target.value)}>{options.map((option)=><option key={option}>{option}</option>)}</select></label>;
}

function TrendChart({values}:{values:number[]}) {
  const data=values.length?values:[0], width=640, height=220, max=Math.max(...data,1);
  const coords=data.map((value,index)=>({value,x:28+index*((width-56)/Math.max(data.length-1,1)),y:height-34-(value/max)*(height-72)}));
  const points=coords.map(({x,y})=>`${x},${y}`).join(" ");
  return <svg className="trend-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Connection requests by visible record: ${data.join(", ")}`}>
    {[0,1,2,3].map((line)=><line key={line} x1="28" x2={width-28} y1={30+line*45} y2={30+line*45} className="gridline"/>)}
    <polyline points={points} className="trend-line-shadow"/><polyline points={points} className="trend-line"/>
    {coords.map(({value,x,y},index)=><g key={`${value}-${index}`}><circle cx={x} cy={y} r="5"/><text x={x} y={y-12} textAnchor="middle">{value}</text></g>)}
  </svg>;
}

function CompletionDonut({completed,total}:{completed:number;total:number}) {
  const rate=total?Math.round(completed/total*100):0, circumference=2*Math.PI*42;
  return <div className="donut-wrap"><svg viewBox="0 0 110 110" role="img" aria-label={`${rate}% of connection requests completed`}><circle className="donut-base" cx="55" cy="55" r="42"/><circle className="donut-value" cx="55" cy="55" r="42" strokeDasharray={`${circumference*rate/100} ${circumference}`} transform="rotate(-90 55 55)"/><text x="55" y="59" textAnchor="middle">{rate}%</text></svg><div><strong>Pathway completion</strong><span>{completed.toLocaleString()} completed of {total.toLocaleString()} requests</span></div></div>;
}

function BarrierHeatmap({records}:{records:typeof countyAccessSeed}) {
  const keys=["transportation","cost","information","digital","language"] as const;
  return <div className="heatmap-scroll"><table className="heatmap"><caption className="sr-only">Barrier index by county; higher values indicate a stronger barrier.</caption><thead><tr><th>County</th>{keys.map((key)=><th key={key}>{key}</th>)}</tr></thead><tbody>{records.map((record)=><tr key={record.id}><th>{record.county}, {record.stateCode}</th>{keys.map((key)=>{const value=record.barriers[key];return <td key={key} style={{background:`hsl(36 55% ${96-value/2.2}%)`}} aria-label={`${key}: ${value}`}><span>{value}</span></td>;})}</tr>)}</tbody></table>{!records.length&&<p className="empty">No counties are available for this comparison.</p>}</div>;
}

function LoadingSkeleton(){return <section className="state-panel" role="status" aria-live="polite"><div className="skeleton wide"/><div className="skeleton"/><div className="skeleton"/><span>Refreshing county information…</span></section>}
function ErrorState({retry}:{retry:()=>void}){return <section className="state-panel error-state" role="alert"><strong>County information could not be refreshed.</strong><p>Your filters are preserved. Please try again.</p><button onClick={retry}>Retry</button></section>}

export default function Platform() {
  const [filters,setFilters]=useState(initialFilters), [toast,setToast]=useState(""), [selectedFips,setSelectedFips]=useState<string|null>(null), [dataState,setDataState]=useState<"ready"|"loading"|"error">("ready");
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const saved=params.get("view")||localStorage.getItem("cbcap-view");if(saved){try{setFilters({...initialFilters,...JSON.parse(saved)});}catch{setToast("The saved view could not be restored.");}}},[]);
  const saveView=()=>{const value=JSON.stringify(filters);localStorage.setItem("cbcap-view",value);const url=new URL(window.location.href);url.searchParams.set("view",value);history.replaceState(null,"",url);setToast("View saved on this device and added to the page link.");};
  const activeFilters=Object.entries(filters).filter(([,value])=>!value.startsWith("All "));
  const stateRecords=useMemo(()=>countyAccessSeed.filter((record)=>filters.state==="All states"||record.state===filters.state),[filters.state]);
  const countyRecords=useMemo(()=>stateRecords.filter((record)=>filters.county==="All counties"||record.county===filters.county),[stateRecords,filters.county]);
  const filtered=useMemo(()=>filterCountyRecords(countyAccessSeed,filters),[filters]);
  const summary=useMemo(()=>aggregateCountyRecords(filtered),[filtered]);
  const selectedRecord=summary.visible.find((record)=>record.fips===selectedFips);
  const topBarriers=useMemo(()=>{const labels={transportation:"Transportation",cost:"Cost",information:"Information gap",digital:"Digital access",language:"Language"};return Object.entries(labels).map(([key,label])=>({label,value:summary.visible.length?Math.round(summary.visible.reduce((sum,record)=>sum+record.barriers[key as keyof typeof record.barriers],0)/summary.visible.length):0})).sort((a,b)=>b.value-a.value);},[summary.visible]);
  const updateFilter=(key:keyof CountyFilters,value:string)=>{setToast("");setFilters((current)=>({...current,[key]:value,...(key==="state"?{county:"All counties",zip:"All ZIP codes"}:{}),...(key==="county"?{zip:"All ZIP codes"}:{})}));};
  const exportCsv=()=>{if(!summary.visible.length)return setToast("No privacy-protected rows are available to export.");downloadFile(`# ${cbcapSeedMetadata.source}\n# ${cbcapSeedMetadata.note}\n${countyRecordsToCsv(filtered)}`,"cbcap-county-export.csv","text/csv;charset=utf-8");setToast(`CSV downloaded with ${summary.visible.length} privacy-protected row${summary.visible.length===1?"":"s"}.`);};
  const downloadBrief=()=>{const filterText=Object.entries(filters).map(([key,value])=>`${key}: ${value}`).join("\n");const brief=`CB-CAP COUNTY ACCESS BRIEF - SAMPLE VIEW\nGenerated: ${new Date().toLocaleDateString()}\n\n${cbcapSeedMetadata.note}\nPrivacy threshold: fewer than ${disclosureControl.minimumCellSize} observations\n\nFILTERS\n${filterText}\n\nVISIBLE SUMMARY\nPeople represented: ${summary.sampleSize}\nConnection requests: ${summary.totalRequests}\nCompleted pathways: ${summary.completedPathways}\nCompletion rate: ${summary.completionRate}%\nMedian connection time: ${summary.medianMinutes} minutes\nAccess index: ${summary.accessIndex}/100\nHubs represented: ${summary.hubs}\nResults withheld for privacy: ${summary.suppressedCount}\n`;downloadFile(brief,"cbcap-county-brief.txt","text/plain;charset=utf-8");setToast("Accessible county brief downloaded.");};
  const printBrief=()=>window.print();

  return <main className="shell"><aside className="rail"><div className="brand"><span>SozoRock</span><small>HEALTH</small></div><div className="product"><strong>CB-CAP</strong><span>County-Based Community<br/>Access Platform</span></div><nav aria-label="CB-CAP sections">{[["Overview","overview"],["Geography","geography"],["Barriers","barriers"],["Counties","counties"],["Trends","trends"],["Reports","reports"]].map(([label,target])=><a key={target} href={`#${target}`}><span aria-hidden="true">-</span>{label}</a>)}</nav><div className="rail-foot"><span className="status-dot"/> Public preview<small>Sample, non-clinical information</small></div></aside>
  <section className="workspace" id="overview"><header className="topbar"><div><p className="eyebrow">National access intelligence</p><h1>{filters.county!=="All counties"?filters.county:filters.state!=="All states"?filters.state:"Nationwide overview"}</h1><p className="lede">See where access pathways are forming, where barriers persist, and where communities may need partnership.</p></div><div className="actions" id="reports"><button className="secondary" onClick={exportCsv}>Export CSV</button><button className="primary" onClick={printBrief}>Print or save <span>PDF</span></button></div></header>
  <div className="data-banner"><div><strong>Sample view</strong><span>This preview shows how CB-CAP presents county information. It does not report current county performance.</span></div><small>Refreshed {cbcapSeedMetadata.refreshedAt}</small></div>
  <section className="filter-panel" aria-label="Dashboard filters"><SelectFilter label="State" value={filters.state} options={["All states",...unique(countyAccessSeed.map((record)=>record.state))]} onChange={(value)=>updateFilter("state",value)}/><SelectFilter label="County" value={filters.county} options={["All counties",...unique(stateRecords.map((record)=>record.county))]} onChange={(value)=>updateFilter("county",value)}/><SelectFilter label="ZIP code" value={filters.zip} options={["All ZIP codes",...unique(countyRecords.map((record)=>record.zip))]} onChange={(value)=>updateFilter("zip",value)}/><SelectFilter label="Period" value={filters.period} options={["All periods",...unique(countyAccessSeed.map((record)=>record.period))]} onChange={(value)=>updateFilter("period",value)}/><SelectFilter label="Hub type" value={filters.hubType} options={["All hub types",...unique(countyAccessSeed.map((record)=>record.hubType))]} onChange={(value)=>updateFilter("hubType",value)}/><SelectFilter label="Language" value={filters.language} options={["All languages",...unique(countyAccessSeed.map((record)=>record.language))]} onChange={(value)=>updateFilter("language",value)}/><SelectFilter label="Primary barrier" value={filters.barrier??"All barriers"} options={["All barriers","transportation","cost","information","digital","language"]} onChange={(value)=>updateFilter("barrier",value)}/><SelectFilter label="Access level" value={filters.accessRange??"All access levels"} options={["All access levels","High (70-100)","Developing (50-69)","Limited (0-49)"]} onChange={(value)=>updateFilter("accessRange",value)}/><button className="clear" onClick={()=>{setFilters(initialFilters);setToast("Filters cleared.");}}>Clear all</button><button className="save-view" onClick={saveView}>Save view</button></section>{activeFilters.length>0&&<div className="filter-chips" aria-label="Active filters">{activeFilters.map(([key,value])=><button key={key} onClick={()=>updateFilter(key as keyof CountyFilters,initialFilters[key as keyof CountyFilters]??"")}>{value} -</button>)}</div>}
  {toast&&<div className="toast" role="status">{toast}<button aria-label="Dismiss message" onClick={()=>setToast("")}>-</button></div>}
  <p className="view-help">Select a highlighted county on the map to open its decision brief.</p>{dataState==="loading"&&<LoadingSkeleton/>}{dataState==="error"&&<ErrorState retry={()=>setDataState("ready")}/>} {dataState==="ready"&&<><section className="metric-grid" aria-label="Filtered access summary"><article><small>People represented</small><strong>{summary.sampleSize.toLocaleString()}</strong><span>Across privacy-protected results</span></article><article><small>Connection requests</small><strong>{summary.totalRequests.toLocaleString()}</strong><span>Selected period and geography</span></article><article><small>Completed pathways</small><strong>{summary.completionRate}%</strong><span>{summary.completedPathways.toLocaleString()} completed</span></article><article><small>Median connection time</small><strong>{summary.medianMinutes||"-"}<sup>{summary.medianMinutes?" min":""}</sup></strong><span>Weighted across visible records</span></article><article><small>Access index</small><strong>{summary.accessIndex||"-"}<sup>{summary.accessIndex?"/100":""}</sup></strong><span>Combined access indicator</span></article></section>
  <section className="visual-grid"><article className="panel map-panel" id="geography"><div className="panel-head"><div><p>Geographic pattern</p><h2>Access index by represented state</h2></div><span className="legend"><i/> Higher index</span></div><AccessMap records={summary.visible} onSelect={setSelectedFips}/></article><article className="panel trend-panel" id="trends"><div className="panel-head"><div><p>Movement</p><h2>Connection requests</h2></div><span>Visible record sequence</span></div><TrendChart values={summary.visible.map((record)=>record.connectionRequests)}/></article><article className="panel barriers-panel" id="barriers"><div className="panel-head"><div><p>Barrier profile</p><h2>Top reported barriers</h2></div><span>Average index</span></div>{topBarriers.map((barrier)=><div className="bar-row" key={barrier.label}><span>{barrier.label}</span><div><i style={{width:`${barrier.value}%`}}/></div><b>{barrier.value}</b></div>)}</article><article className="panel table-panel" id="counties"><div className="panel-head"><div><p>County detail</p><h2>Privacy-protected records</h2></div><span>{summary.visible.length} visible - {summary.suppressedCount} withheld for privacy</span></div><div className="table-scroll"><table><thead><tr><th>County</th><th>State</th><th>ZIP</th><th>Hub</th><th>Language</th><th>Requests</th><th>Completed</th><th>Index</th></tr></thead><tbody>{summary.visible.map((record)=><tr key={record.id}><td>{record.county}</td><td>{record.stateCode}</td><td>{record.zip}</td><td>{record.hubType}</td><td>{record.language}</td><td>{record.connectionRequests}</td><td>{record.completedPathways}</td><td><b>{record.accessIndex}</b></td></tr>)}{!summary.visible.length&&<tr><td colSpan={8} className="empty">No records match this view. Try broadening the filters.</td></tr>}</tbody></table></div></article><article className="panel donut-panel"><div className="panel-head"><div><p>Composition</p><h2>Request outcomes</h2></div></div><CompletionDonut completed={summary.completedPathways} total={summary.totalRequests}/></article><article className="panel heatmap-panel"><div className="panel-head"><div><p>County comparison</p><h2>Barrier intensity</h2></div><span>0-100 barrier index</span></div><BarrierHeatmap records={summary.visible}/></article></section></>}
  {selectedRecord&&<aside className="county-drawer" data-testid="county-decision-drawer" aria-label={`${selectedRecord.county} decision brief`}><button className="drawer-close" onClick={()=>setSelectedFips(null)} aria-label="Close county brief">-</button><p className="eyebrow">County decision brief</p><h2>{selectedRecord.county}, {selectedRecord.stateCode}</h2><div className="drawer-score"><strong>{selectedRecord.accessIndex}</strong><span>Access index<br/>National sample benchmark: 65</span></div><h3>What stands out</h3><p>{selectedRecord.barriers.transportation>=70?"Transportation is the strongest barrier in this view. Local access points and navigation support may reduce missed connections.":"Access is near the sample benchmark, with targeted gaps still visible."}</p><h3>Non-clinical actions</h3><ul><li>Confirm current library and community access points.</li><li>Invite licensed providers serving this state to verify availability.</li><li>Review language and low-bandwidth support with local partners.</li></ul><button className="primary" onClick={downloadBrief}>Download county brief</button><small>Sample information · No clinical recommendation</small></aside>}<footer className="privacy"><div className="privacy-icon">i</div><div><strong>Privacy threshold applied</strong><p>Results representing fewer than {disclosureControl.minimumCellSize} observations are withheld from metrics, charts, tables, and downloads. This preview contains no personal or clinical information.</p></div><a href="#data-methodology" onClick={(event)=>{event.preventDefault();setToast("Methodology: sample county-level records, privacy thresholds, weighted summary measures, and no individual-level data.");}}>View methodology</a></footer></section></main>;
}
