import Link from "next/link";
import { CountyPreview, type CountyChoice } from "./CountyPreview";
import copy from "./product-contract.json";

export function PublicProduct({ counties }: { counties: CountyChoice[] }) {
  return <div className="cb-product">
    <a className="skip-link" href="#product">Skip to product</a>
    <header className="cb-top"><Link href="/" className="cb-wordmark" aria-label="CB-CAP home">CB-CAP<span>SozoRock Foundation</span></Link><nav aria-label="CB-CAP"><a href="#product">Product</a><a href="#organizations">For Organizations</a><a href="#methods">Methods</a><Link href="/workspace">Sign in</Link></nav></header>
    <main>
      <section className="cb-hero" id="product" aria-labelledby="product-heading"><span className="cb-kicker">{copy.descriptor}.</span><h1 id="product-heading">From evidence to a plan <em>you can defend.</em></h1><p>{copy.heroBody}</p><div className="cb-actions"><a className="cb-primary" href="#county">Explore a county <span aria-hidden="true">↗</span></a><a href="#organizations">For organizations</a></div><small>{copy.trustLine}</small></section>
      <section className="cb-county-section" id="county" aria-labelledby="county-heading"><div className="cb-section-intro"><span className="cb-kicker">Public Evidence Preview</span><h2 id="county-heading">See the county picture.</h2><p>Start with a county. See health conditions, access barriers and the evidence behind them. Compare what matters without turning one score into the answer.</p><p className="cb-aside">For open public evidence exploration, visit <a href="https://health.sozorockfoundation.org/explore">Place Intelligence</a>.</p></div><CountyPreview counties={counties} /></section>
      <section className="cb-plan-story" aria-labelledby="plan-heading"><div><span className="cb-kicker">Plan</span><h2 id="plan-heading">Turn evidence<br />into a plan.</h2></div><div><p className="cb-large">Bring public data, local records and community knowledge together. Organize CHA/CHIP evidence, test options, name an owner and set the next review.</p><dl className="cb-plan-questions"><div><dt>What belongs in our plan?</dt><dd>Evidence with an exact source.</dd></div><div><dt>What could we do?</dt><dd>Test Options with labeled assumptions.</dd></div><div><dt>What can I take into the meeting?</dt><dd>A source-linked brief for human review.</dd></div></dl><p className="cb-aside">Institutional planning requires authorized access and active evidence sources.</p></div></section>
      <section className="cb-resource-story" aria-labelledby="resources-heading"><header><span className="cb-kicker">Resources</span><h2 id="resources-heading">Line up the resources.</h2><p>See what a response may require across funding, budget and workforce before it becomes a commitment.</p></header><div className="cb-resource-lines"><div><h3>Funding Fit</h3><p>What opportunities fit the evidence? What is still missing?</p></div><div><h3>Budget &amp; Funding</h3><p>What is already funded? What is grant-dependent? What changes when assumptions change?</p></div><div><h3>Workforce &amp; Capacity</h3><p>What capacity evidence matters before the plan moves forward?</p></div></div><p className="cb-aside">These institutional capabilities require reviewed sources and production activation. They are not available in this public preview.</p></section>
      <section className="cb-monitor-story" aria-labelledby="monitor-heading"><span className="cb-kicker">What Changed</span><h2 id="monitor-heading">Keep the plan current.</h2><p>Evidence changes. Funding closes. Plans expire. Assumptions change. The institutional workflow is designed to show what changed so teams know what needs another look.</p><p className="cb-aside">Monitoring requires active sources, a responsible owner and review dates. No live monitoring is implied by this preview.</p></section>
      <section className="cb-trust-story" id="methods" aria-labelledby="trust-heading"><span className="cb-kicker">Methods</span><h2 id="trust-heading">Built for public scrutiny.</h2><p className="cb-large">Sources stay visible.<br />Assumptions stay labeled.<br />Missing data stays missing.<br />People review consequential outputs.</p><div className="cb-methods"><details><summary>How evidence becomes planning material</summary><p>Evidence → Interpretation → Lever is the methodology behind CB-CAP, the County-Based Community Access Platform. Rethinking Rural Governance supplies the conceptual systems-intelligence foundation. It is not a source for current health estimates or proof of statistical validation.</p><p>The maturity model runs from Data Capture through Operational Execution, Structured Integration, Systems Intelligence and Institutional Intelligence. Current public evidence does not imply that every domain is active.</p></details><details><summary>Sources, assumptions and limits</summary><p>The preview uses source-vintaged Census geography and CDC PLACES county estimates. County, city and ZIP-linked evidence remain distinct. Published estimates, user assumptions and planning scenarios must stay distinguishable. No proprietary composite is the default answer.</p><p>Any optional Planning View must show its components, formula, weights, coverage and missingness. It is not a government designation, county grade, funding formula, causal model, clinical-risk score or validated county ranking.</p></details><details><summary>Human review and public-data boundaries</summary><p>AI drafts. People decide. CB-CAP does not diagnose, prescribe, allocate funding, set county priorities or replace CHA/CHIP governance. The public preview contains no resident records or PHI. Local Evidence requires authorized access, review and exact document citations.</p></details></div></section>
      <section className="cb-organizations" id="organizations" aria-labelledby="organizations-heading"><span className="cb-kicker">For organizations</span><h2 id="organizations-heading">Bring local context<br />to the planning room.</h2><p>Public evidence is a starting point. Organizations can use authorized institutional workflows to connect reviewed local evidence with planning, resources and decisions.</p><p>Institutional access is not currently available in this release. The public preview remains open.</p><div className="cb-actions"><a className="cb-primary" href="https://www.sozorockfoundation.org/partner">Contact the Foundation <span aria-hidden="true">↗</span></a><Link href="/workspace">Planning Workspace</Link></div></section>
    </main><footer className="cb-footer"><strong>CB-CAP</strong><p>{copy.descriptor}.</p><a href="https://www.sozorockfoundation.org">The SozoRock Foundation, Inc.</a></footer>
  </div>;
}
